// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace webproj.Migrations
{
    [DbContext(typeof(SajtContext))]
    [Migration("20220317204701_vf")]
    partial class vf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Igra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GodinaIzlaska")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Zanr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Igra");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CenaIgre")
                        .HasColumnType("int");

                    b.Property<int?>("IgraFKID")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaProdatih")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IgraFKID");

                    b.ToTable("Prodavnica");
                });

            modelBuilder.Entity("Models.Recenzija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Duzina")
                        .HasColumnType("int");

                    b.Property<int?>("IgraFKID")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikFKID")
                        .HasColumnType("int");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ID");

                    b.HasIndex("IgraFKID");

                    b.HasIndex("KorisnikFKID");

                    b.ToTable("Recenzija");
                });

            modelBuilder.Entity("Models.Sysreq", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FreeSpace")
                        .HasColumnType("int");

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IgraFKID")
                        .HasColumnType("int");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IgraFKID");

                    b.ToTable("Sysreq");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.HasOne("Models.Igra", "IgraFK")
                        .WithMany("Prodavnice")
                        .HasForeignKey("IgraFKID");

                    b.Navigation("IgraFK");
                });

            modelBuilder.Entity("Models.Recenzija", b =>
                {
                    b.HasOne("Models.Igra", "IgraFK")
                        .WithMany("Recenzije")
                        .HasForeignKey("IgraFKID");

                    b.HasOne("Models.Korisnik", "KorisnikFK")
                        .WithMany()
                        .HasForeignKey("KorisnikFKID");

                    b.Navigation("IgraFK");

                    b.Navigation("KorisnikFK");
                });

            modelBuilder.Entity("Models.Sysreq", b =>
                {
                    b.HasOne("Models.Igra", "IgraFK")
                        .WithMany("Sysreqs")
                        .HasForeignKey("IgraFKID");

                    b.Navigation("IgraFK");
                });

            modelBuilder.Entity("Models.Igra", b =>
                {
                    b.Navigation("Prodavnice");

                    b.Navigation("Recenzije");

                    b.Navigation("Sysreqs");
                });
#pragma warning restore 612, 618
        }
    }
}
